# Generated by Django 2.2.5 on 2019-11-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequestsModel',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=30)),
                ('rcontact', models.IntegerField()),
                ('rarea', models.CharField(max_length=30)),
                ('rblood', models.CharField(max_length=10)),
            ],
        ),
    ]
