# Generated by Django 2.2.5 on 2019-11-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequestsmodel',
            name='ridno',
            field=models.IntegerField(default=False),
        ),
    ]
