# Generated by Django 2.2.5 on 2019-11-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage_app', '0002_bloodrequestsmodel_ridno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequestsmodel',
            name='ridno',
        ),
    ]
