# Generated by Django 2.2.5 on 2019-11-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorDetailsModel',
        ),
    ]
